package main

func nicknames() []string {
	nickname := []string{
		"Blinky",
		"Boxers",
		"Bud",
		"Calamity",
		"Castanets",
		"Casters on Crutches",
		"Champagne Cork",
		"Cheese and Wine",
		"Cheeseburger",
		"Chicken Sandwich",
		"Curiously Dense",
		"Dart-Hurling",
		"Dive Bar",
		"Fancypants",
		"Fast Fingers",
		"Flotsam",
		"Gopher",
		"Hamburger",
		"High School Sweetheart",
		"Jetsam",
		"Kobold Lips",
		"Laser Beams",
		"Mac",
		"Margarine",
		"Marginal",
		"Marigold",
		"Marvin the Martini",
		"Melvin",
		"Metal Objects",
		"Multiple",
		"Narcissus",
		"Orc Pajamas",
		"Palm Trees",
		"Pelican",
		"Petunia",
		"Pew-Pew-Pew",
		"Phlegmy",
		"Powderpuff",
		"Railroad Tracks",
		"Rheumy",
		"Rock and a Hard Place",
		"Salami Hog",
		"Salisbury Steak",
		"Shuffleboard-Playin'",
		"Slow Dance",
		"Smooth Operator",
		"Soccer Balls",
		"Spider",
		"Submarine",
		"Submariner",
		"Sunken Treasure",
		"Taco",
		"Tarantula",
		"Teen Heartthrob",
		"The Elbow",
		"The Kitten",
		"The Knickerbocker",
		"The Neck",
		"The Repeat Offender",
		"The Sloth",
		"The Slug",
		"The Tiger",
		"Turnpike",
		"Two-Teeth",
		"Winky",
		"99.9 Fahrenheit Degrees",
		"Acetylene",
		"Acetylene Jim",
		"Afterburner",
		"Arson",
		"Ashtray",
		"Barbecue",
		"Blaze",
		"Blisterin'",
		"Brimstone",
		"Briquette",
		"Burn Ward",
		"Conflagration",
		"Do You Smell Something Burning?",
		"Embers",
		"Fahrenheit 151",
		"Fireball",
		"Firebird",
		"Firebrand",
		"Fireworks",
		"Hot Sauce",
		"Jabañero",
		"Jalapeño",
		"Magma",
		"Several Hundred Degrees",
		"Smolderin' Doug",
		"Solar Flare",
		"Sparky",
		"Swelterin'",
		"The Arsonist",
		"The Back Burner",
		"The Bunsen Burner",
		"The Flamer",
		"The Flaming Bindlestiff",
		"The Flaming Flamer",
		"The Flaming Kebab",
		"The Torch",
		"The Vermin Igniter",
		"Trashfire",
		"Volcano",
		"Absolute Zero",
		"Anti-antifreeze",
		"Black Ice",
		"Blizzard",
		"Bluelips",
		"Brainfreeze",
		"Chatterin'",
		"Chilly Willy",
		"Cold As Ice",
		"Coolerator",
		"Don't Get Your Tongue Stuck To Him",
		"Freezerburn",
		"Freezing Point",
		"Frigid Jim",
		"Frigidaire",
		"Frostbite",
		"Frosty",
		"Frozenfoot",
		"Glacial",
		"Hypothermia",
		"Ice Nine",
		"Ice Storm",
		"Iceberg",
		"Icebox",
		"Icecube",
		"Icemaker",
		"Icicle",
		"Liquid Nitrogen",
		"Mr. Freeze",
		"Mr. Sleet",
		"Really Cold Extremities",
		"Snowball",
		"Snowflake",
		"Snowman",
		"The Polar Bear",
		"The Snowman",
		"Wind Chill",
		"Yeti-Boy",
		"Spooky",
		"Abracadaver",
		"Bogeyman",
		"Boneyard",
		"Boo",
		"Braaaain-Cravin'",
		"Chain-Rattlin'",
		"Collywobbles",
		"Corpsey",
		"Creepy Jim",
		"Deadeye",
		"Ghoulicious",
		"Gives You the Jibblies",
		"Golgotha",
		"Goosepimples",
		"Gravedigger",
		"Graverobber",
		"Heebie-Jeebies",
		"Hemp Dance",
		"Jack Ketch",
		"Lich Licker",
		"Mass-Murderin'",
		"Mass Grave",
		"Mother Issues",
		"Old Scratch",
		"Reaperman",
		"Screaming Meemie",
		"Skullface",
		"Soulless",
		"Spooky Eyes",
		"Voodoo-doin'",
		"Stench",
		"Awful Offal",
		"Baron von Stinkyfish",
		"Bad-Smellin' Saul",
		"Bath-Allergic",
		"Flatulator",
		"Gag-A-Maggot",
		"Garlic Press",
		"Gas-Passin'",
		"Gym Clothes",
		"Halitosis",
		"Lavatory",
		"Limburger Jim",
		"Liver 'n' Onions",
		"Loo Brush",
		"Midden",
		"Musty",
		"Nauseating Bouquet",
		"No Soap, Thank You",
		"Old Milk",
		"Only One Pair of Socks",
		"Pitstain",
		"Poo-Flinger",
		"Poo-Gas",
		"Potent Joe",
		"Public Toilet",
		"Rottencrotch",
		"Sardine-Breath",
		"Sir Reeksalot",
		"Smell-So-Bad",
		"Smelly",
		"Spitstink",
		"Stinkpalm",
		"Stinkspit",
		"Stinkyfeet",
		"Stinkyfinger",
		"Sulfur-Eatin'",
		"Swampy",
		"The Walking Toilet",
		"Things That Smell Bad",
		"Underarms",
		"Astro-Glide",
		"Bad Touch",
		"Banana Hammock",
		"Belljingler",
		"Bowtier",
		"Canecandier",
		"Cookiebaker",
		"Dolldresser",
		"Figgypudding",
		"Fruitcaker",
		"Fudgeboxer",
		"Giftwrapper",
		"Halldecker",
		"Horsecarver",
		"Jackintheboxer",
		"Kiteflier",
		"Mistletoestringer",
		"Navidad",
		"Nutcracker",
		"Piebaker",
		"Ribbonwinder",
		"Sauerkraut",
		"Sleighbeller",
		"Stockingstuffer",
		"Taffypuller",
		"Teddystuffer",
		"Tinselstringer",
		"Topspinner",
		"Toypacker",
		"Treetopper",
		"Treetrimmer",
		"Turducken",
		"Turkeybaster",
		"Turkeyblaster",
		"Wenceslaus",
		"Wreathweaver",
		"the Assistant Manager",
		"the Alaska-Phobe",
		"the Alien Pod-Person",
		"the Amityville Horror",
		"the Aristocrat",
		"the Assistant Manager",
		"the Back-Alley Taxidermist",
		"the Bedazzler",
		"the Bent-Knee Yahoo",
		"the Bird-Headed Fool",
		"the Boneyard Concierge",
		"the Boxcar Beekeeper",
		"the Boxcar Medic",
		"the Breakdancin' Fool",
		"the Brokeback Mountaineer",
		"the Buddha",
		"the Chamberlain",
		"the Child-Size",
		"the Child with Haunting Eyes",
		"the Colchester Kid",
		"the Curator",
		"the Devil",
		"the Dilettante",
		"the Docent",
		"the Drunk",
		"the Duck Throttler",
		"the Dumpster Archaeologist",
		"the Elderly",
		"the Enigma Machine",
		"the Eternal Mystery",
		"the Expert Dreamweaver",
		"the Explorer",
		"the Family Man",
		"the Freakster",
		"the Freightyard Satan",
		"the Fruit Pie Magician",
		"the Future of Hoboing",
		"the Gentleman",
		"the Giant Rabbit",
		"the Gnome Kicker",
		"the Gourmand",
		"the Hairless",
		"the High-Ranking Mason",
		"the Hobo Cyborg",
		"the Hobo Einstein",
		"the Hobo From Both Mars and Venus",
		"the Hobo in the Iron Mask",
		"the Hobo On Stilts",
		"the Hobo With Good Credit",
		"the Human Gizzard",
		"the Human Shark",
		"the Human Toothpick",
		"the Human Tunneler",
		"the Humanist",
		"the Infirm",
		"the Ionizer",
		"the Jack Mormon",
		"the Jackanapes",
		"the Ladies' Man",
		"the Land Pirate",
		"the Long Island Landscaper",
		"the Lumberjack",
		"the Lumberjack Mormon",
		"the Mad Monk",
		"the Man of the Hour",
		"the Man of the Year",
		"the Man with the Handlebar Eyebrows",
		"the Many-Bearded",
		"the Merovingian",
		"the Minuscule",
		"the Moistener",
		"the Monkey Man",
		"the Monsoon",
		"the Newfoundland Screech",
		"the Northerner",
		"the Ombudsman",
		"the Ornamentalist",
		"the Patriarch",
		"the Personal Trainer",
		"the Pirate",
		"the Poor Dad",
		"the President's Long-Lost Brother",
		"the Prodigal Halfwit",
		"the Prosthetic Hobo",
		"the Pumpkin-Patch Crooner",
		"the Railbender",
		"the Rich Man's Poor Man",
		"the Right Hand of Telly Savalas",
		"the Salad Shooter",
		"the San Francisco Treat",
		"the Scientist",
		"the Scientologist Scientist",
		"the Scoliosis Sufferer",
		"the Scratcher",
		"the Secret Collector of Decorative China",
		"the Secret Cop",
		"the Sexual Elf",
		"the Sneak Thief",
		"the Southern Officer and the Southern Gentleman",
		"the Spark-Spitter",
		"the Spiral-Cut Ham",
		"the Star-Traveler",
		"the Strangetalker",
		"the Strong",
		"the Tapdancing Trombo",
		"the Tree Surgeon",
		"the Train-Oyster",
		"the Trainyard Aristotle",
		"the Vandal",
		"the Very, Very Disturbed",
		"the Vestigial Man",
		"the Viscount of Everywhere",
		"the Walking Disagreement",
		"the Waltz King",
		"the Waterproof Man",
		"the Wax Poet",
		"the Well Prepared",
		"the Whistlin' Kidnapper",
		"Ultralord of the Hobo Jungle",
		"Who Isn't Right in the Head",
		"Who May Be Found by the Card Catalog",
		"Whose Pants Are Indestructible",
		"the Brimstone Bumpkin",
		"the Capsaicin Kid",
		"the Cigar-Butt-Flicker",
		"the Cinder-Tosser",
		"the Coal-Chucker",
		"the Devil's Pitchfork",
		"the Dry Heat",
		"the Felonious Firebrand",
		"the Fire-Eater",
		"the Flame Belcher",
		"the Free-Range Oven",
		"the Guy Who Causes a Temperature-Related Desire to Remove All of One's Clothing",
		"the Heartburn Kid",
		"the Heatstroke Kid",
		"the Hobo On Fire",
		"the Hoboñero Jabo",
		"the Human Barbecue",
		"the Human Campfire",
		"the Human Flamethrower",
		"the Human Tiki-Torch",
		"the Infernal Racketeer",
		"the Inferno",
		"the Inflammable Man",
		"the Insanely Feverish",
		"the Kerosene Kid",
		"the Kid Whose Hair Is On Fire",
		"the Magmagician",
		"the Man Who Burns Like Burning",
		"the Man Who Feels Hot, Hot, Hot",
		"the Molten Man",
		"the Red-Hot Poker",
		"the Roman Candelabra",
		"the Sidewalk Egg-Fryer",
		"the Sterno Connoisseur",
		"the Sweltering Sauna Sitter",
		"the Tabasco Man",
		"the Walking Stove",
		"the Walking Sunburn",
		"Who Burns at Both Ends",
		"Who Is Hot Because He's Fly",
		"Who Is Hot, Hot, So Hot, Sticky Sweet",
		"the Abominable Hobo",
		"the Alabama Iceberg",
		"the Arctic Circular",
		"the Arctic Tramp",
		"the Boston Penguin",
		"the Chilliest Hobo",
		"the Cincinnati Snocone Machine",
		"the Cold Miser",
		"the Dry Icicle",
		"the Earl of Frostbite",
		"the Fallen Snow-Angel",
		"the Freezerburn Kid",
		"the Freezin' Frenchman",
		"the Guy For Whom the Eskimos Have One Hundred Different Words",
		"the Guy With Icewater In His Veins But Probably Not Literally",
		"the Hazy Shade of Winter",
		"the Hobo-Shaped Ice Sculpture",
		"the Hobo Who Looks a Bit Like a Penguin",
		"the Hobosicle",
		"the Human Icebox",
		"the Human Zamboni",
		"the Ice Cream of the Future",
		"the Ice Cube Cowboy",
		"the Iceman who Cometh",
		"the Indifferent Stare of a Former Lover",
		"the Liquid-Nitrogen Man",
		"the Little Fonzie (And What's Fonzie Like?)",
		"the Meat Popsicle",
		"the Pennsylvania Snowman",
		"the Polar Express",
		"the Polar Hobo",
		"the Polar Ice Capped",
		"the Prehistoric Iceman",
		"the Refrigerator Coil",
		"the Shiverin' Shanker",
		"the Snowball-Tosser",
		"the Temperature at which Revenge is Best Served",
		"the Too-Cold Ice Baby",
		"the Witch's Teat in a Cast-Iron Bra",
		"the World's Most Violent Eskimo",
		"the Amateur Necromancer",
		"the Autopsist",
		"the Black-Eyed, Pasty Asian Kid",
		"the Bloody-Aproned",
		"the Bony-Fingered Creep",
		"the Boogity Man",
		"the Cemetery Casanova",
		"the Corpse Groom",
		"the Crypt Creeper",
		"the Dancin' Corpse",
		"the Dead Man Walking",
		"the Eldritch Mist",
		"the Empty Eye Socket",
		"the Evil-Eyed",
		"the Fingerbone Collector",
		"the Galloping Ghoul",
		"the Grim Panhandler",
		"the Guy Who Likes Corpses a Little Too Much, If You Know What I Mean",
		"the Guy With Little Mouths Where His Eyes Should Be",
		"the Haunted Hobo",
		"the Hobo of the Shadow of Death",
		"the Hobo Who Goes Bump in the Night",
		"the Hobo Who Wants Your Delicious Brains",
		"the Hobosferatu",
		"the Hockey-Masked Marauder",
		"the Hook-Handed Lurker",
		"the Long, Red-Legged Scissor Man",
		"the Maniacal Laugher",
		"the Night Stalker",
		"the Sauntering Corpse",
		"the Shambling Man",
		"the Silent Hillbilly",
		"the Tap-Dancing Skeleton",
		"the Tommyknocker Man",
		"the Walking Dead Guy",
		"Undead Detective",
		"Who Hides In The Shadows",
		"Who May Be a Zombie",
		"Who Sings Nursery Rhymes in a High-Pitched Voice While Delicately Caressing a Straight Razor",
		"Whose Clothes Are Made out of Suspiciously Pale Leather",
		"He Who Smelt It And Therefore Dealt It",
		"the Dead Man, Judging by the Smell",
		"the Dumpster Sleeper",
		"the Filth Merchant",
		"the Filthy",
		"the Foul",
		"the Foulness-in-Chief of Stankonia",
		"the Fustulent Crack",
		"the Garbage Collector",
		"the Guy Made Entirely Out of Onions Or At Least That's How He Smells",
		"the Guy Who Chain-Smokes in a Poorly Ventilated Room",
		"the Guy Who Eats Nothing But Limburger Cheese",
		"the Hobo of Eternal Stench",
		"the Hobo Who Breaks Like the Wind",
		"the Hobo Who Doesn't Have the Sense to Disregard His Own Feces",
		"the Hobo Who Sleeps With the Pigs",
		"the Human Compost Heap",
		"the Human Dung Beetle",
		"the Human Paper Mill",
		"the Human Stinkbomb",
		"the Man Who Should Probably Change His Socks",
		"the Man Who Should Probably Change His Underwear, Like, Now",
		"the Man Who Uses a Rotting Fish for Aftershave",
		"the Master of Flatulence",
		"the Methane Man",
		"the Nonbather",
		"the Nose Exploder",
		"the Odoriffic",
		"the Poopsmith",
		"the Rotten-Egg-Tosser",
		"the Rotten Meat Vendor",
		"the Sewer-Bather",
		"the Smelliest Hobo In the World, Probably",
		"the Stankmaster",
		"the Sulfuric Wonder",
		"the Sultan of Stink",
		"the Unidentifiable Smell",
		"Who Has Never Bathed Ever",
		"Who Is Extremely Funky But Not In a Good Way",
		"Who Smells Like Bad Meat or Good Cheese",
		"the Special Hugger",
		"the 32-Year-Old Guy At The Junior Prom",
		"the Assless Chapper",
		"the Bad Toucher",
		"the Balding Guy with a Greasy Ponytail",
		"the Bottom Pincher",
		"the Cameraphone Panty-shot Taker",
		"the Dapper Dan Man",
		"the Dirty Jokester",
		"the Face Licker",
		"the Free-Candy-Dispenser",
		"the Furtive Glance",
		"the Grade School Loiterer",
		"the Guy Who Casually Brushes Up Against You Way Too Often for It to Be a Coincidence",
		"the Guy Who Does Not Have a Pencil in His Pocket",
		"the Guy Who Was Kicked Out of the Frat House for Misogynistic Behavior",
		"the Guy Who Works the Ferris Wheel at the County Fair",
		"the Guy Your Parents Were Specifically Referring To When They Said Not To Talk To Strangers",
		"the Heavy Breather",
		"the Hugger",
		"the Human Leer",
		"the Human Stain",
		"the Inappropriate",
		"the Inappropriate Kisser",
		"the Liplickin' Perv",
		"the Midnight Groper",
		"the Moustache You Don't Trust",
		"the Moustache-Waxer",
		"the Ogler",
		"the Peeping Tom",
		"the Pocket Pool Shark",
		"the Snake-Oil Salesman",
		"the Suggestive Winker",
		"the Too-Slow Streaker",
		"the Uncle Who's Not Really Your Uncle",
		"the Unrated Version",
		"the Used Car Salesman",
		"the Wolf-Whistler",
		"Who Looks Down Your Shirt",
		"Who Will Poka Da Nipples",
		"the Bell Jingler",
		"the Carol Crooner",
		"the Crimbo Tradition",
		"the Decorator",
		"the Festively Festooned",
		"the Festooner",
		"the Fruity as a Nut Cake",
		"the Gaily Appareled",
		"the Gift Wrapper",
		"the Hall Decker",
		"the Holly Hanger",
		"the Little Drummer Boy",
		"the Merry Gentleman",
		"the Mistletoe Bandit",
		"the Nut Cracker",
		"the Nutty as a Fruit Cake",
		"the One Who Waits Under the Mistletoe",
		"the Polar Expressionist",
		"the Reindeer Groomer",
		"the Sleigh Bell Polisher",
		"the Sleigh Bell Ringer",
		"the Snowman Builder",
		"the Snowmannequin",
		"the Stocking Stuffer",
		"the Sugarplum Visionary",
		"the Tree Trimmer",
		"the Ubiquitous Music that Grates on your Ears after Two Minutes",
		"the White Crimbo Dreamer",
		"the Wreath Wrangler",
		"Who Came Upon the Midnight Clear",
		"Who Got Run Over By a Reindeer",
		"Who Is As Frightful As the Weather Outside",
		"Who Lets It Snow",
		"Who May Or May Not Be Home For Crimbo",
		"4 Stroke",
		"Fisherman",
		"Nails",
		"Adonis",
		"Flames",
		"Numbers",
		"All City",
		"Fox",
		"O Dog",
		"Almighty Blood Messiah",
		"Freckles",
		"O.G.",
		"Animal",
		"Free Style",
		"Old Creepy",
		"Ant",
		"Frosty",
		"Peanuts",
		"Artichoke King",
		"FUBAR",
		"Pee Wee",
		"Baby Face",
		"Gangsta C",
		"Phones",
		"Baldo",
		"Ghost",
		"Pit Bull",
		"Bananas",
		"Goldie",
		"Playboy",
		"Barber",
		"Greasy Thumb",
		"Plumber",
		"Bats",
		"Gremlin",
		"Popcorn",
		"Big G",
		"Grim Reaper",
		"Pretty Boy",
		"Blaze",
		"Ha-Ha",
		"Princess",
		"Bloodhound",
		"Hatchet",
		"Razor",
		"Blue Eyes",
		"Head Busta",
		"Red Face",
		"Books",
		"Ice Cube",
		"Repo Girl",
		"Boot",
		"Iceman",
		"Rifleman",
		"Bow Wow",
		"Ice T",
		"Scarface",
		"Boxcars",
		"Icepick",
		"Scars",
		"Brains",
		"Jelly",
		"Scratch",
		"Bronx",
		"Johnny Sausage",
		"Shadow",
		"Bugs",
		"Kermit",
		"Shaggy",
		"Bugsy",
		"Kid Blast",
		"Sharpie",
		"Bull",
		"Kid Twist",
		"Silver Dollar",
		"Burnout",
		"Killing Machine",
		"Slingshot",
		"Butterfingers",
		"Knots",
		"Smallville",
		"Camel",
		"Lil Loco",
		"Smiley",
		"Caveman",
		"Lil Man",
		"Smoke",
		"Channel 4",
		"Lips",
		"Snake",
		"Chicken Man",
		"Little Insane",
		"Sneakers",
		"Chin",
		"Little Nicky",
		"Socks",
		"Chongo",
		"Little Red",
		"Soft Hammer",
		"Clouds",
		"Lord High Executioner",
		"Sonny Black",
		"Clown",
		"Love Candy",
		"Spoon",
		"Cool Daddy Cake",
		"Lucky",
		"Sticks",
		"Cranky",
		"Machine Gun",
		"Taco",
		"Cruiser",
		"Mad Dog",
		"Teflon Don",
		"Cuts",
		"Mad Hatter",
		"Three Fingers",
		"Dapper Don",
		"Manic Maniac",
		"Toto",
		"Dasher",
		"Master Blaster",
		"Trigger Mike",
		"Dentist",
		"Matches",
		"Two Holes",
		"Digger",
		"Maverick",
		"Vixen",
		"Dogs",
		"Mega Flex",
		"Wadd",
		"Droopy",
		"Messiah",
		"Wheels",
		"Easy Z",
		"Midnight",
		"Wild Child",
		"Endo",
		"Mom",
		"Wild Man",
		"Enforcer",
		"Monster",
		"Witch",
		"Fangs",
		"Murda King",
		"Wolf",
		"Fast Trigger",
		"Muscles",
		"Young G",
		"Fat Boy",
		"Music Man",
		"Zookeeper",
		"Needles",
	}
	return nickname
}
